name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install -y node npm
          npm install

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Generate Views
        run: npm run compile

      - name: Build
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: cmake --build ${{github.workspace}}/build
