name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  linux-build:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Views
        run: npm run compile

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build


  macos-build:
    name: macOS
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Generate Views
        run: npm run compile

      - name: Configure CMake
        run: |
          cmake -B build \
            -DBUILD_V8_RENDERER=off

      - name: Build
        run: cmake --build build


  windows-build:
    name: Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            mingw-w64-x86_64-ninja

      - name: Install Dependencies
        run: npm install

      - name: Generate Views
        run: npm run compile

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          cmake -B build \
            -DBUILD_V8_RENDERER=off

      - name: Build
        shell: msys2 {0}
        run: cmake --build build